### ISSUE TITLE
MacOS - Intel Core I5

### ISSUE THREAD

**Issue by dmarro89** [gomlx/gopjrt#10]
Hi,
I'm trying to install gopjrt on MacOS with Intel Core I5 in order to use gomlx but I have some issues.
Is it supported or am I missing something?

Thanks

**Comment by janpfeifer** [comment]
hi @dmarro89 , I apologize, I haven't built it to Mac/amd-64, only arm-64. And I just added an explicit mention of it in the `README.md` to clarify that (sorry for the confusion), it's coming in a larger PR in a little bit later today.

Having said that, if you are feeling "brave", it might simply work, if one manages to:

1. Manually compiling the C/C++ wrapper in ([`github.com/gomlx/gopjrt/c`])(https://github.com/gomlx/gopjrt/tree/main/c) -- this is the XLA wrapper GoMLX uses.
2. Manually compile a CPU PJRT (a dynamically linked library that is the "engine" of a XLA for a specific platform)  from [`github.com/openxla/xla/`](https://github.com/openxla/xla/) (the rule to build is `bazel build //xla/pjrt/c:pjrt_c_api_cpu_plugin.so`)

Sadly, I don't have access to mac boxes to run/maintain pre-built binaries for there :(

**Comment by dmarro89** [comment]
Hi @janpfeifer thanks for your answer.
I'll try later to build it.
I'll let you updated about it.

Thanks

**Comment by janpfeifer** [comment]
Thanks! And pls do let me know how it goes. If you are successful, I'd be happy to include the prebuilt Mac/amd64 build in to the release.

**Comment by dmarro89** [comment]
@janpfeifer sorry to bother you, correct me if I am wrong.
For the point 1 ->
> Manually compiling the C/C++ wrapper in [github.com/gomlx/gopjrt/c](https://github.com/gomlx/gopjrt/tree/main/c) -- this is the XLA wrapper GoMLX uses.

I have updated the bazel.sh and the open_xla_bazelrc in order to get the amd build. Now that it's done, where I should put the build generated ?

**Comment by janpfeifer** [comment]
No bother at all! I'm so happy you are doing this, it would be awesome to see this working in Darwin (both amd64 and arm64).  

I would love if you created a PR with the changes..

About separating the build rules per architecture, there are the following files:

- `open_xla_bazelrc` and `open_xla_bazelrc.version` generally doesn't need to be written, since it's the same for all architectures and it's pulled automatically again by `bazel.sh`.  I should have included them in the `.gitignore` -- you may want to do that, or I'll do that shortly after your PR.
- `bazel.sh`: I assume you added another `if / then / else` for the new architecture right ? Pls, just create the PR that will be awesome 😃 

Now, after you build a CPU PJRT for darwin/amd64 it would be nice also to create a `cmd/install_darwin_amd64`. But it can come later -- and it will depend on updating the release to include the binary prebuilts.

**Comment by dmarro89** [comment]
Thanks for your fast answer.
- open_xla_bazelrc and open_xla_bazelrc.version are not in the .gitignore - I can add them.
- Yes, I have just added a new if else for the new architecture (and just changed a couple things to get worked on macos).
I'll create the PR including these changes and the new install_darwin_amd64.
My question is how to include the binary prebuilts ?

**Comment by dmarro89** [comment]
FYI, I have tried to train my first Neural Network with your library and it's going (on darwin amd64).
Do you have any slack workspace where we can chat ?

Thanks

**Comment by janpfeifer** [comment]
hi Davide, thank you so much for the PR!! ❤️  It looks awesome, and I'm so happy it worked. Also, it's nice to see it worked with Jax PJRT plugin for CPU (I assume this is the PJRT plugin you used, right ?).

I'm merging it and making a few changes (in the next half-hour):

- Your additions to `openxla_xla_bazelrc` I'm adding to a separate `darwin_amd64_bazelrc` file, and added it to be read, because `openxla_xla_bazelrc` is overwritten ... No worries, I'll add it to a `.gitignore`.
- Renaming `cmd/install_darwin_amd.sh` to `cmd/install_darwin_amd64.sh`, just to keep consistency.
- Added the entries in `README.md`, because if it's not documented it's as if it's not there 😄 

But let's sync up. I'll send a message to you in LinkedIn, maybe we can coordinate there.

**Comment by dmarro89** [comment]
Hi @janpfeifer,
ok thanks!

Can I ask you a quick review?
I'm trying to execute your gomlx [examples](https://github.com/gomlx/gomlx/blob/main/examples/linear/linear.go) but I'm getting an error of segmentation violation while calling -> call_PJRT_Client_Compile method.

I'll do a small recap just to be sure I have done everything.

- [X] I have run the bazel.sh under gopjrt/c to get the library built for my darwin/amd. I got 1 file (libgomlx_xlabuilder.a) and a folder "include" ->  both moved under /usr/local/lib.
- [X]  I have built the [xla](https://github.com/openxla/xla/) project running bazel build //xla/pjrt/c:pjrt_c_api_cpu_plugin.so -> generated output under xla/bazel-bin

Then I have added to my go program execution these three env vars:

1. "CGO_ENABLED": "1",
2. "CGO_LDFLAGS": "-L/usr/local/lib -lgomlx_xlabuilder -framework CoreFoundation" -> needed because it is getting an error while building
3. "PJRT_PLUGIN_LIBRARY_PATH": "/PROJECT_PATH/xla/bazel-bin/xla/pjrt/c/" -> in order to get the pjrt_c_api_cpu_plugin.so file.

When I run the program, I'm getting a segmentation fault (SIGSEGV) during a CGO call in the gomlx library -> pjrt._Cfunc_call_PJRT_Client_Compile -> pjrtClientCompile.

I think I'm missing something on xla.

**Comment by janpfeifer** [comment]
hi Davide, sorry you are blocked on this. So, before using GoMLX, simplest would be to try to get `gopjrt` tests to work. They will require a working PJRT plugin.

If you checkout `gopjrt`, just go to `pjrt/` or even `xlabuilder/` directory and do a `go test.` ... I would assume it would SIGSEGV as well.

Now, it's odd that it seg faults, usually I tried to code defensively and handle all errors (and report them). Would you mind copy&pasting the exact output here ?

**Comment by janpfeifer** [comment]
Btw, I'm working on trying to get cross-compilation to work, normalizing the names and paths of the prebuild files, adding the Darwin/Amd64 to README, see PR #12  -- still under work, I'm loosing so much time with Bazel cryptic-ness ... 😞 ... not even the AI can handle it :smile:  (or see the https://github.com/gomlx/gopjrt/tree/damd)

**Comment by janpfeifer** [comment]
Just for an update for others reading this:

1. I tried to build a Darwin/Intel (x86_64) on MacOS Sequoia, and while XlaBuilder seems to build correctly, I'm not able to build a CPU PJRT using https://github.com/openxla/xla. I started a thread on their Discord channel on this.
2. I'm create a new minor release for `gopjrt`, and I'm including the updates to the bazel files that build the XlaBuilder C-wrapper that works on Darwin/x86_64, but I'm not mentioning it in the documentation, because it's not working. Either in the future OpenXLA/XLA makes the PJRT work, or we clean it up and give up on it -- hopefully a Go only CPU backend will be available this year (or early next) (without XLA) and that will work in Darwin/x86_64, no promises, but maybe ...
